version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: python3 main.py

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    working_dir: /app
    command: npm run dev